import { connectDb } from "./connect.db";
import { UrlProps } from "./getUrl";

/**
 * Generates a slug string using the randomUUID function and returns the last
 * four characters.
 *
 * @return {string} The slug string generated by the function.
 */
function generateSlug(): string {
	return Math.random().toString(36).slice(-4);
}

/**
 * Creates a new URL in the database with a generated slug based on the provided original URL.
 *
 * @param {string} url - The original URL to be saved in the database.
 * @return {Promise<string>} Returns the newly created slug.
 */
export async function createUrl(url: string): Promise<string> {
	const db = await connectDb();
	const slug = generateSlug();
	// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
	await db.models.url.create<Pick<UrlProps, "original" | "slug">>({
		slug,
		original: url,
	});

	return slug;
}
